language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-23
  - android-28
  - extra-android-m2repository

script:
  - ./gradlew Library:assemble --console=plain
  - ./gradlew Plugin:assemble --console=plain
  - ./gradlew Library:lint --console=plain
  - ./gradlew Plugin:test --console=plain
  - ./gradlew Library:test --console=plain